
package plataforma.admin.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmpleadoService", targetNamespace = "http://services.admin.plataforma/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmpleadoService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hi", targetNamespace = "http://services.admin.plataforma/", className = "plataforma.admin.services.Hi")
    @ResponseWrapper(localName = "hiResponse", targetNamespace = "http://services.admin.plataforma/", className = "plataforma.admin.services.HiResponse")
    @Action(input = "http://services.admin.plataforma/EmpleadoService/hiRequest", output = "http://services.admin.plataforma/EmpleadoService/hiResponse")
    public String hi(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "helloworld", targetNamespace = "http://services.admin.plataforma/", className = "plataforma.admin.services.Helloworld")
    @ResponseWrapper(localName = "helloworldResponse", targetNamespace = "http://services.admin.plataforma/", className = "plataforma.admin.services.HelloworldResponse")
    @Action(input = "http://services.admin.plataforma/EmpleadoService/helloworldRequest", output = "http://services.admin.plataforma/EmpleadoService/helloworldResponse")
    public String helloworld();

}
