//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioDocente
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MateriaDocente", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class MateriaDocente : object
    {
        
        private int anioField;
        
        private string carreraField;
        
        private string diaField;
        
        private int idField;
        
        private string instanciaField;
        
        private string nombreField;
        
        private string turnoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int anio
        {
            get
            {
                return this.anioField;
            }
            set
            {
                this.anioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string carrera
        {
            get
            {
                return this.carreraField;
            }
            set
            {
                this.carreraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dia
        {
            get
            {
                return this.diaField;
            }
            set
            {
                this.diaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string instancia
        {
            get
            {
                return this.instanciaField;
            }
            set
            {
                this.instanciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string turno
        {
            get
            {
                return this.turnoField;
            }
            set
            {
                this.turnoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlumnoMateria", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class AlumnoMateria : object
    {
        
        private float Nota_CursadaField;
        
        private float Nota_DefinitivaField;
        
        private string apellidoField;
        
        private int dniField;
        
        private int idField;
        
        private int id_inscripcionField;
        
        private int idcatedraField;
        
        private string nombreField;
        
        private ServicioDocente.NotasParciales[] notasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Nota_Cursada
        {
            get
            {
                return this.Nota_CursadaField;
            }
            set
            {
                this.Nota_CursadaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Nota_Definitiva
        {
            get
            {
                return this.Nota_DefinitivaField;
            }
            set
            {
                this.Nota_DefinitivaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellido
        {
            get
            {
                return this.apellidoField;
            }
            set
            {
                this.apellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int dni
        {
            get
            {
                return this.dniField;
            }
            set
            {
                this.dniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_inscripcion
        {
            get
            {
                return this.id_inscripcionField;
            }
            set
            {
                this.id_inscripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idcatedra
        {
            get
            {
                return this.idcatedraField;
            }
            set
            {
                this.idcatedraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicioDocente.NotasParciales[] notas
        {
            get
            {
                return this.notasField;
            }
            set
            {
                this.notasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotasParciales", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class NotasParciales : object
    {
        
        private System.TimeSpan Tiempo_limiteField;
        
        private System.DateTime fecha_cargaField;
        
        private int idusuario_materia_cuatrimestreField;
        
        private float notaField;
        
        private int nro_parcialField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Tiempo_limite
        {
            get
            {
                return this.Tiempo_limiteField;
            }
            set
            {
                this.Tiempo_limiteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_carga
        {
            get
            {
                return this.fecha_cargaField;
            }
            set
            {
                this.fecha_cargaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idusuario_materia_cuatrimestre
        {
            get
            {
                return this.idusuario_materia_cuatrimestreField;
            }
            set
            {
                this.idusuario_materia_cuatrimestreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float nota
        {
            get
            {
                return this.notaField;
            }
            set
            {
                this.notaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nro_parcial
        {
            get
            {
                return this.nro_parcialField;
            }
            set
            {
                this.nro_parcialField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlumnoMateriaNotaRequest", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class AlumnoMateriaNotaRequest : object
    {
        
        private float NotaField;
        
        private int idEstudianteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Nota
        {
            get
            {
                return this.NotaField;
            }
            set
            {
                this.NotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEstudiante
        {
            get
            {
                return this.idEstudianteField;
            }
            set
            {
                this.idEstudianteField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioDocente.IService")]
    public interface IService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMateriasDocente", ReplyAction="http://tempuri.org/IService/GetMateriasDocenteResponse")]
        ServicioDocente.GetMateriasDocenteResponse GetMateriasDocente(ServicioDocente.GetMateriasDocenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMateriasDocente", ReplyAction="http://tempuri.org/IService/GetMateriasDocenteResponse")]
        System.Threading.Tasks.Task<ServicioDocente.GetMateriasDocenteResponse> GetMateriasDocenteAsync(ServicioDocente.GetMateriasDocenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAlumnosMateria", ReplyAction="http://tempuri.org/IService/GetAlumnosMateriaResponse")]
        ServicioDocente.GetAlumnosMateriaResponse GetAlumnosMateria(ServicioDocente.GetAlumnosMateriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAlumnosMateria", ReplyAction="http://tempuri.org/IService/GetAlumnosMateriaResponse")]
        System.Threading.Tasks.Task<ServicioDocente.GetAlumnosMateriaResponse> GetAlumnosMateriaAsync(ServicioDocente.GetAlumnosMateriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMaterias", ReplyAction="http://tempuri.org/IService/GetMateriasResponse")]
        ServicioDocente.GetMateriasResponse GetMaterias(ServicioDocente.GetMateriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMaterias", ReplyAction="http://tempuri.org/IService/GetMateriasResponse")]
        System.Threading.Tasks.Task<ServicioDocente.GetMateriasResponse> GetMateriasAsync(ServicioDocente.GetMateriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpsertNotasCursada", ReplyAction="http://tempuri.org/IService/UpsertNotasCursadaResponse")]
        ServicioDocente.UpsertNotasCursadaResponse UpsertNotasCursada(ServicioDocente.UpsertNotasCursadaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpsertNotasCursada", ReplyAction="http://tempuri.org/IService/UpsertNotasCursadaResponse")]
        System.Threading.Tasks.Task<ServicioDocente.UpsertNotasCursadaResponse> UpsertNotasCursadaAsync(ServicioDocente.UpsertNotasCursadaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMateriasDocente", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMateriasDocenteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idDocente;
        
        public GetMateriasDocenteRequest()
        {
        }
        
        public GetMateriasDocenteRequest(int idDocente)
        {
            this.idDocente = idDocente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMateriasDocenteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMateriasDocenteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServicioDocente.MateriaDocente[] GetMateriasDocenteResult;
        
        public GetMateriasDocenteResponse()
        {
        }
        
        public GetMateriasDocenteResponse(ServicioDocente.MateriaDocente[] GetMateriasDocenteResult)
        {
            this.GetMateriasDocenteResult = GetMateriasDocenteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAlumnosMateria", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAlumnosMateriaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idMateria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int idDocente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool esFinal;
        
        public GetAlumnosMateriaRequest()
        {
        }
        
        public GetAlumnosMateriaRequest(int idMateria, int idDocente, bool esFinal)
        {
            this.idMateria = idMateria;
            this.idDocente = idDocente;
            this.esFinal = esFinal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAlumnosMateriaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAlumnosMateriaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServicioDocente.AlumnoMateria[] GetAlumnosMateriaResult;
        
        public GetAlumnosMateriaResponse()
        {
        }
        
        public GetAlumnosMateriaResponse(ServicioDocente.AlumnoMateria[] GetAlumnosMateriaResult)
        {
            this.GetAlumnosMateriaResult = GetAlumnosMateriaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMaterias", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMateriasRequest
    {
        
        public GetMateriasRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMateriasResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMateriasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServicioDocente.MateriaDocente[] GetMateriasResult;
        
        public GetMateriasResponse()
        {
        }
        
        public GetMateriasResponse(ServicioDocente.MateriaDocente[] GetMateriasResult)
        {
            this.GetMateriasResult = GetMateriasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpsertNotasCursada", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpsertNotasCursadaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idCatedra;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int nroParcial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public ServicioDocente.AlumnoMateriaNotaRequest[] listadoAlumnos;
        
        public UpsertNotasCursadaRequest()
        {
        }
        
        public UpsertNotasCursadaRequest(int idCatedra, int nroParcial, ServicioDocente.AlumnoMateriaNotaRequest[] listadoAlumnos)
        {
            this.idCatedra = idCatedra;
            this.nroParcial = nroParcial;
            this.listadoAlumnos = listadoAlumnos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpsertNotasCursadaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpsertNotasCursadaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UpsertNotasCursadaResult;
        
        public UpsertNotasCursadaResponse()
        {
        }
        
        public UpsertNotasCursadaResponse(string UpsertNotasCursadaResult)
        {
            this.UpsertNotasCursadaResult = UpsertNotasCursadaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IServiceChannel : ServicioDocente.IService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<ServicioDocente.IService>, ServicioDocente.IService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceClient() : 
                base(ServiceClient.GetDefaultBinding(), ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServicioDocente.GetMateriasDocenteResponse GetMateriasDocente(ServicioDocente.GetMateriasDocenteRequest request)
        {
            return base.Channel.GetMateriasDocente(request);
        }
        
        public System.Threading.Tasks.Task<ServicioDocente.GetMateriasDocenteResponse> GetMateriasDocenteAsync(ServicioDocente.GetMateriasDocenteRequest request)
        {
            return base.Channel.GetMateriasDocenteAsync(request);
        }
        
        public ServicioDocente.GetAlumnosMateriaResponse GetAlumnosMateria(ServicioDocente.GetAlumnosMateriaRequest request)
        {
            return base.Channel.GetAlumnosMateria(request);
        }
        
        public System.Threading.Tasks.Task<ServicioDocente.GetAlumnosMateriaResponse> GetAlumnosMateriaAsync(ServicioDocente.GetAlumnosMateriaRequest request)
        {
            return base.Channel.GetAlumnosMateriaAsync(request);
        }
        
        public ServicioDocente.GetMateriasResponse GetMaterias(ServicioDocente.GetMateriasRequest request)
        {
            return base.Channel.GetMaterias(request);
        }
        
        public System.Threading.Tasks.Task<ServicioDocente.GetMateriasResponse> GetMateriasAsync(ServicioDocente.GetMateriasRequest request)
        {
            return base.Channel.GetMateriasAsync(request);
        }
        
        public ServicioDocente.UpsertNotasCursadaResponse UpsertNotasCursada(ServicioDocente.UpsertNotasCursadaRequest request)
        {
            return base.Channel.UpsertNotasCursada(request);
        }
        
        public System.Threading.Tasks.Task<ServicioDocente.UpsertNotasCursadaResponse> UpsertNotasCursadaAsync(ServicioDocente.UpsertNotasCursadaRequest request)
        {
            return base.Channel.UpsertNotasCursadaAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:63598/Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService,
        }
    }
}
