//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudianteService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estudiante", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class Estudiante : object
    {
        
        private string direccionField;
        
        private string emailField;
        
        private int idField;
        
        private string passwordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Analitico", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class Analitico : object
    {
        
        private EstudianteService.Materia[] listadoNotasField;
        
        private float promedio_generalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EstudianteService.Materia[] listadoNotas
        {
            get
            {
                return this.listadoNotasField;
            }
            set
            {
                this.listadoNotasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float promedio_general
        {
            get
            {
                return this.promedio_generalField;
            }
            set
            {
                this.promedio_generalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Materia", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class Materia : object
    {
        
        private float examen_finalField;
        
        private string nombreField;
        
        private float nota_cursadaField;
        
        private float nota_definitivaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float examen_final
        {
            get
            {
                return this.examen_finalField;
            }
            set
            {
                this.examen_finalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float nota_cursada
        {
            get
            {
                return this.nota_cursadaField;
            }
            set
            {
                this.nota_cursadaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float nota_definitiva
        {
            get
            {
                return this.nota_definitivaField;
            }
            set
            {
                this.nota_definitivaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Catedra", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class Catedra : object
    {
        
        private string cuatrimestreField;
        
        private string diaField;
        
        private bool es_finalField;
        
        private System.DateTime fechaField;
        
        private int idcatedraField;
        
        private string inscriptoField;
        
        private string materiaField;
        
        private string profesorField;
        
        private string turnoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cuatrimestre
        {
            get
            {
                return this.cuatrimestreField;
            }
            set
            {
                this.cuatrimestreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dia
        {
            get
            {
                return this.diaField;
            }
            set
            {
                this.diaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool es_final
        {
            get
            {
                return this.es_finalField;
            }
            set
            {
                this.es_finalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idcatedra
        {
            get
            {
                return this.idcatedraField;
            }
            set
            {
                this.idcatedraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string inscripto
        {
            get
            {
                return this.inscriptoField;
            }
            set
            {
                this.inscriptoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string materia
        {
            get
            {
                return this.materiaField;
            }
            set
            {
                this.materiaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string profesor
        {
            get
            {
                return this.profesorField;
            }
            set
            {
                this.profesorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string turno
        {
            get
            {
                return this.turnoField;
            }
            set
            {
                this.turnoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EstudianteService.IService")]
    public interface IService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateModificacionDatos", ReplyAction="http://tempuri.org/IService/UpdateModificacionDatosResponse")]
        EstudianteService.UpdateModificacionDatosResponse UpdateModificacionDatos(EstudianteService.UpdateModificacionDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateModificacionDatos", ReplyAction="http://tempuri.org/IService/UpdateModificacionDatosResponse")]
        System.Threading.Tasks.Task<EstudianteService.UpdateModificacionDatosResponse> UpdateModificacionDatosAsync(EstudianteService.UpdateModificacionDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InscripcionAlumno", ReplyAction="http://tempuri.org/IService/InscripcionAlumnoResponse")]
        EstudianteService.InscripcionAlumnoResponse InscripcionAlumno(EstudianteService.InscripcionAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InscripcionAlumno", ReplyAction="http://tempuri.org/IService/InscripcionAlumnoResponse")]
        System.Threading.Tasks.Task<EstudianteService.InscripcionAlumnoResponse> InscripcionAlumnoAsync(EstudianteService.InscripcionAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteInscripcionAlumno", ReplyAction="http://tempuri.org/IService/DeleteInscripcionAlumnoResponse")]
        EstudianteService.DeleteInscripcionAlumnoResponse DeleteInscripcionAlumno(EstudianteService.DeleteInscripcionAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteInscripcionAlumno", ReplyAction="http://tempuri.org/IService/DeleteInscripcionAlumnoResponse")]
        System.Threading.Tasks.Task<EstudianteService.DeleteInscripcionAlumnoResponse> DeleteInscripcionAlumnoAsync(EstudianteService.DeleteInscripcionAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SelectInformeAnalitico", ReplyAction="http://tempuri.org/IService/SelectInformeAnaliticoResponse")]
        EstudianteService.SelectInformeAnaliticoResponse SelectInformeAnalitico(EstudianteService.SelectInformeAnaliticoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SelectInformeAnalitico", ReplyAction="http://tempuri.org/IService/SelectInformeAnaliticoResponse")]
        System.Threading.Tasks.Task<EstudianteService.SelectInformeAnaliticoResponse> SelectInformeAnaliticoAsync(EstudianteService.SelectInformeAnaliticoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/TraerInscripcionesDisponibles", ReplyAction="http://tempuri.org/IService/TraerInscripcionesDisponiblesResponse")]
        EstudianteService.TraerInscripcionesDisponiblesResponse TraerInscripcionesDisponibles(EstudianteService.TraerInscripcionesDisponiblesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/TraerInscripcionesDisponibles", ReplyAction="http://tempuri.org/IService/TraerInscripcionesDisponiblesResponse")]
        System.Threading.Tasks.Task<EstudianteService.TraerInscripcionesDisponiblesResponse> TraerInscripcionesDisponiblesAsync(EstudianteService.TraerInscripcionesDisponiblesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateModificacionDatos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateModificacionDatosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EstudianteService.Estudiante datos;
        
        public UpdateModificacionDatosRequest()
        {
        }
        
        public UpdateModificacionDatosRequest(EstudianteService.Estudiante datos)
        {
            this.datos = datos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateModificacionDatosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateModificacionDatosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UpdateModificacionDatosResult;
        
        public UpdateModificacionDatosResponse()
        {
        }
        
        public UpdateModificacionDatosResponse(string UpdateModificacionDatosResult)
        {
            this.UpdateModificacionDatosResult = UpdateModificacionDatosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InscripcionAlumno", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InscripcionAlumnoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idusuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int idcatedra;
        
        public InscripcionAlumnoRequest()
        {
        }
        
        public InscripcionAlumnoRequest(int idusuario, int idcatedra)
        {
            this.idusuario = idusuario;
            this.idcatedra = idcatedra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InscripcionAlumnoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InscripcionAlumnoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string InscripcionAlumnoResult;
        
        public InscripcionAlumnoResponse()
        {
        }
        
        public InscripcionAlumnoResponse(string InscripcionAlumnoResult)
        {
            this.InscripcionAlumnoResult = InscripcionAlumnoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteInscripcionAlumno", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteInscripcionAlumnoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idusuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int idcatedra;
        
        public DeleteInscripcionAlumnoRequest()
        {
        }
        
        public DeleteInscripcionAlumnoRequest(int idusuario, int idcatedra)
        {
            this.idusuario = idusuario;
            this.idcatedra = idcatedra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteInscripcionAlumnoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteInscripcionAlumnoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string DeleteInscripcionAlumnoResult;
        
        public DeleteInscripcionAlumnoResponse()
        {
        }
        
        public DeleteInscripcionAlumnoResponse(string DeleteInscripcionAlumnoResult)
        {
            this.DeleteInscripcionAlumnoResult = DeleteInscripcionAlumnoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectInformeAnalitico", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectInformeAnaliticoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idusuario;
        
        public SelectInformeAnaliticoRequest()
        {
        }
        
        public SelectInformeAnaliticoRequest(int idusuario)
        {
            this.idusuario = idusuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectInformeAnaliticoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectInformeAnaliticoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EstudianteService.Analitico SelectInformeAnaliticoResult;
        
        public SelectInformeAnaliticoResponse()
        {
        }
        
        public SelectInformeAnaliticoResponse(EstudianteService.Analitico SelectInformeAnaliticoResult)
        {
            this.SelectInformeAnaliticoResult = SelectInformeAnaliticoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TraerInscripcionesDisponibles", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TraerInscripcionesDisponiblesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idUsuario;
        
        public TraerInscripcionesDisponiblesRequest()
        {
        }
        
        public TraerInscripcionesDisponiblesRequest(int idUsuario)
        {
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TraerInscripcionesDisponiblesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TraerInscripcionesDisponiblesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EstudianteService.Catedra[] TraerInscripcionesDisponiblesResult;
        
        public TraerInscripcionesDisponiblesResponse()
        {
        }
        
        public TraerInscripcionesDisponiblesResponse(EstudianteService.Catedra[] TraerInscripcionesDisponiblesResult)
        {
            this.TraerInscripcionesDisponiblesResult = TraerInscripcionesDisponiblesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IServiceChannel : EstudianteService.IService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<EstudianteService.IService>, EstudianteService.IService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceClient() : 
                base(ServiceClient.GetDefaultBinding(), ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public EstudianteService.UpdateModificacionDatosResponse UpdateModificacionDatos(EstudianteService.UpdateModificacionDatosRequest request)
        {
            return base.Channel.UpdateModificacionDatos(request);
        }
        
        public System.Threading.Tasks.Task<EstudianteService.UpdateModificacionDatosResponse> UpdateModificacionDatosAsync(EstudianteService.UpdateModificacionDatosRequest request)
        {
            return base.Channel.UpdateModificacionDatosAsync(request);
        }
        
        public EstudianteService.InscripcionAlumnoResponse InscripcionAlumno(EstudianteService.InscripcionAlumnoRequest request)
        {
            return base.Channel.InscripcionAlumno(request);
        }
        
        public System.Threading.Tasks.Task<EstudianteService.InscripcionAlumnoResponse> InscripcionAlumnoAsync(EstudianteService.InscripcionAlumnoRequest request)
        {
            return base.Channel.InscripcionAlumnoAsync(request);
        }
        
        public EstudianteService.DeleteInscripcionAlumnoResponse DeleteInscripcionAlumno(EstudianteService.DeleteInscripcionAlumnoRequest request)
        {
            return base.Channel.DeleteInscripcionAlumno(request);
        }
        
        public System.Threading.Tasks.Task<EstudianteService.DeleteInscripcionAlumnoResponse> DeleteInscripcionAlumnoAsync(EstudianteService.DeleteInscripcionAlumnoRequest request)
        {
            return base.Channel.DeleteInscripcionAlumnoAsync(request);
        }
        
        public EstudianteService.SelectInformeAnaliticoResponse SelectInformeAnalitico(EstudianteService.SelectInformeAnaliticoRequest request)
        {
            return base.Channel.SelectInformeAnalitico(request);
        }
        
        public System.Threading.Tasks.Task<EstudianteService.SelectInformeAnaliticoResponse> SelectInformeAnaliticoAsync(EstudianteService.SelectInformeAnaliticoRequest request)
        {
            return base.Channel.SelectInformeAnaliticoAsync(request);
        }
        
        public EstudianteService.TraerInscripcionesDisponiblesResponse TraerInscripcionesDisponibles(EstudianteService.TraerInscripcionesDisponiblesRequest request)
        {
            return base.Channel.TraerInscripcionesDisponibles(request);
        }
        
        public System.Threading.Tasks.Task<EstudianteService.TraerInscripcionesDisponiblesResponse> TraerInscripcionesDisponiblesAsync(EstudianteService.TraerInscripcionesDisponiblesRequest request)
        {
            return base.Channel.TraerInscripcionesDisponiblesAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:63599/Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService,
        }
    }
}
